---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ingress-class: nginx
  name: petclinic-ingress
  namespace: petclinic  
spec:
  ingressClassName: nginx
  rules:
  - host: www.1-jo.com
    http:
      paths:
      - path: /                  # 모든 경로를 petclinic 서비스로 전달
        pathType: Prefix
        backend:
          service:
            name: petclinic-service
            port:
              number: 80
